### ISSUE TITLE
Properly set pagecoroutines

### ISSUE THREAD

**Issue by scrapenetwork** [elacuesta/scrapy-pyppeteer#10]
Hey im having trouble how to properly set

pagecoroutine and
Navigationpagecoroutine

using your example 

    def start_requests(self):
        yield scrapy.Request(
            url="http://quotes.toscrape.com/scroll",
            meta=dict(
                pyppeteer=True,
                pyppeteer_page_coroutines=[
                    PageCoroutine("waitForSelector", "div.quote"),
                    PageCoroutine("evaluate", "window.scrollBy(0, 2000)"),
                    PageCoroutine("waitForSelector", "div.quote:nth-child(11)"),  # 10 per page
                ],
            ),
        )

does not pass start requests
Error 
“Name” ‘pagecoroutine’ is not defined

Is it possible to edit for a working example?

**Comment by elacuesta** [comment]
Those examples don't include all the necessary imports for the sake of brevity. You should be able to solve the issue by adding:

```python
from scrapy_pyppeteer.page import PageCoroutine, NavigationPageCoroutine
```

**Comment by elacuesta** [comment]
Updated in 4100ef93aed1e4473f69ac8aea23b4c46bd1af08 and 037a5a5083b23413a7326d56c2462738c59e0787, closing.
