### ISSUE TITLE
Set User Agent

### ISSUE THREAD

**Issue by XioYang23** [elacuesta/scrapy-pyppeteer#5]
Hey looking for the correct way to change/set the user agent

Ive tried
```python
PYPPETEER_LAUNCH_OPTIONS={
  'headless':False,
  'agrs':[(
    'userAgent','THE USER AGENT VALUE HERE'
    )]
}
```
 &
```python
await page.setUserAgent('userAgent','UA VALUE HERE')
await pyppeteer.page.Page.setUserAgent('userAgent','UA VALUE HERE')
```
 &
```python
await page.setUserAgent('UA VALUE HERE')
await pyppeteer.page.Page.setUserAgent('UA VALUE HERE')
```
ive done a mixture of these, with all the same results.

None of these set the user-agent value and code still uses the default chrome 71 agent

the default ua= 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3542.0 Safari/537.36\\

**Comment by elacuesta** [comment]
Hi! The simplest way is probably to modify the [`USER_AGENT`](https://docs.scrapy.org/en/latest/topics/settings.html#user-agent) Scrapy setting. See the following example:

```python
import logging

import scrapy
import pyppeteer

logging.getLogger("pyppeteer").setLevel(logging.INFO)
logging.getLogger("websockets").setLevel(logging.INFO)

class UserAgentSpider(scrapy.Spider):
    name = "user_agent"
    custom_settings = {
        "USER_AGENT": "The Magic Words are Squeamish Ossifrage",
        "DOWNLOAD_HANDLERS": {
            "https": "scrapy_pyppeteer.handler.ScrapyPyppeteerDownloadHandler",
        },
    }

    def start_requests(self):
        yield scrapy.Request("https://httpbin.org/headers", meta=dict(pyppeteer=True))

    async def parse(self, response, page: pyppeteer.page.Page):
        await page.screenshot(options={"path": "headers.png"})
        await page.close()
```

`scrapy runspider user_agent.py -s TWISTED_REACTOR=twisted.internet.asyncioreactor.AsyncioSelectorReactor`
then produces the following screenshot:
![headers](https://user-images.githubusercontent.com/1731933/95664850-d7f64780-0b21-11eb-8156-cccbba93b7f4.png)

Additionally, you could use the [`DEFAULT_REQUEST_HEADERS`](https://docs.scrapy.org/en/latest/topics/settings.html#default-request-headers) setting, or handle it on a per-request basis by providing a value for the `User-Agent` key in the `headers` parameter when creating each [`Request`](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request).

Thanks for using this package!

**Comment by XioYang23** [comment]
Hey apologize for the late response

Using:
```python
class UserAgentSpider(scrapy.Spider):
    name = "user_agent"
    custom_settings = {
        "USER_AGENT": "THIS IS WHERE THE USERAGENT IS ",
        "DOWNLOAD_HANDLERS": {
            "https": "scrapy_pyppeteer.handler.ScrapyPyppeteerDownloadHandler",
        },
    }
```
That seems to work at the response from scrapy
Pyppeteer seems to still use a different user agent 

Example:
```
[D:pyppeteer.connection.Connection]
\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3542.0 Safari/537.36\"}
```
from the log, its using this user agent^

```
[scrapy.core.engine] DEBUG: Crawled (200) <GET > (referer: None) ['pyppeteer']
{b'User-Agent': [b'THIS IS WHERE THE USERAGENT IS ']}
```
Then scrapy kicks in at the response 




Any way to change the request agent?

(edited for syntax highlighting)

**Comment by elacuesta** [comment]
Request headers are updated [here](https://github.com/elacuesta/scrapy-pyppeteer/blob/v0.0.14/scrapy_pyppeteer/handler.py#L39-L46) (notice they are only updated for "intentional" requests, i.e., not secondary requests triggered by the browser like images, stylesheets, fonts, etc). I think what you are observed can be caused by one of the following:
1. The message corresponds to one of those secondary requests.
2. The message corresponds to a request from Scrapy, but it's logged before the headers are updated.

Regarding (1), I will update the above function so all requests include the defined User Agent header. Regarding (2), I can just tried with the above spider (https://github.com/elacuesta/scrapy-pyppeteer/issues/5#issuecomment-706611044), which makes only one request, and by commenting out the `logging.getLogger("pyppeteer").setLevel(logging.INFO)` line you can see that the original User Agent from Chrome does appear in some messages, however the updated one is the one that actually reaches the website.

**Comment by XioYang23** [comment]
![Screen Shot 2020-12-18 at 8 42 00 PM](https://user-images.githubusercontent.com/33576094/102677837-687c8400-4172-11eb-80d4-86b953fce858.png)


It appears as the browsers user agent here is a photo of chrome telling me agent is outdated,
even tho ive added the latest its not the reading it correctly it seems, thxs

Also amazing middleware , love playing around with it! Thxs alot!

**Comment by elacuesta** [comment]
Right, the default Chrome version comes bundled with the upstream `pyppeteer` package, but you can override it by setting `PYPPETEER_LAUNCH_OPTIONS = {"executablePath": "/path/to/a/specific/chrome/binary"}`
